// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orm.proto

package orm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LiqRiskTemplateRequest1 struct {
	LiquidationRiskConfig *LiquidationRiskConfig `protobuf:"bytes,1,opt,name=liquidationRiskConfig,proto3" json:"liquidationRiskConfig,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *LiqRiskTemplateRequest1) Reset()         { *m = LiqRiskTemplateRequest1{} }
func (m *LiqRiskTemplateRequest1) String() string { return proto.CompactTextString(m) }
func (*LiqRiskTemplateRequest1) ProtoMessage()    {}
func (*LiqRiskTemplateRequest1) Descriptor() ([]byte, []int) {
	return fileDescriptor_917d186095e2832b, []int{0}
}

func (m *LiqRiskTemplateRequest1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiqRiskTemplateRequest1.Unmarshal(m, b)
}
func (m *LiqRiskTemplateRequest1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiqRiskTemplateRequest1.Marshal(b, m, deterministic)
}
func (m *LiqRiskTemplateRequest1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiqRiskTemplateRequest1.Merge(m, src)
}
func (m *LiqRiskTemplateRequest1) XXX_Size() int {
	return xxx_messageInfo_LiqRiskTemplateRequest1.Size(m)
}
func (m *LiqRiskTemplateRequest1) XXX_DiscardUnknown() {
	xxx_messageInfo_LiqRiskTemplateRequest1.DiscardUnknown(m)
}

var xxx_messageInfo_LiqRiskTemplateRequest1 proto.InternalMessageInfo

func (m *LiqRiskTemplateRequest1) GetLiquidationRiskConfig() *LiquidationRiskConfig {
	if m != nil {
		return m.LiquidationRiskConfig
	}
	return nil
}

type LiqRiskTemplateResponse1 struct {
	LiqRiskTemplates     *LiquidationRiskConfig `protobuf:"bytes,1,opt,name=liqRiskTemplates,proto3" json:"liqRiskTemplates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LiqRiskTemplateResponse1) Reset()         { *m = LiqRiskTemplateResponse1{} }
func (m *LiqRiskTemplateResponse1) String() string { return proto.CompactTextString(m) }
func (*LiqRiskTemplateResponse1) ProtoMessage()    {}
func (*LiqRiskTemplateResponse1) Descriptor() ([]byte, []int) {
	return fileDescriptor_917d186095e2832b, []int{1}
}

func (m *LiqRiskTemplateResponse1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiqRiskTemplateResponse1.Unmarshal(m, b)
}
func (m *LiqRiskTemplateResponse1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiqRiskTemplateResponse1.Marshal(b, m, deterministic)
}
func (m *LiqRiskTemplateResponse1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiqRiskTemplateResponse1.Merge(m, src)
}
func (m *LiqRiskTemplateResponse1) XXX_Size() int {
	return xxx_messageInfo_LiqRiskTemplateResponse1.Size(m)
}
func (m *LiqRiskTemplateResponse1) XXX_DiscardUnknown() {
	xxx_messageInfo_LiqRiskTemplateResponse1.DiscardUnknown(m)
}

var xxx_messageInfo_LiqRiskTemplateResponse1 proto.InternalMessageInfo

func (m *LiqRiskTemplateResponse1) GetLiqRiskTemplates() *LiquidationRiskConfig {
	if m != nil {
		return m.LiqRiskTemplates
	}
	return nil
}

func init() {
	proto.RegisterType((*LiqRiskTemplateRequest1)(nil), "LiqRiskTemplateRequest1")
	proto.RegisterType((*LiqRiskTemplateResponse1)(nil), "LiqRiskTemplateResponse1")
}

func init() { proto.RegisterFile("orm.proto", fileDescriptor_917d186095e2832b) }

var fileDescriptor_917d186095e2832b = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xbf, 0x4a, 0x03, 0x41,
	0x10, 0xc6, 0x39, 0x0b, 0xc1, 0x49, 0xa3, 0x07, 0x26, 0x97, 0x90, 0x42, 0xae, 0x12, 0x8b, 0x3d,
	0x2e, 0x76, 0x96, 0xb1, 0x3d, 0x11, 0x4e, 0x6b, 0x61, 0xbd, 0x8c, 0xcb, 0xe0, 0xee, 0xce, 0xde,
	0xfe, 0x09, 0x82, 0x9d, 0xaf, 0xe0, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x18, 0x05, 0x91, 0x5c, 0x48,
	0xb9, 0xfc, 0xbe, 0xdf, 0x7e, 0x33, 0x03, 0x47, 0xec, 0x8d, 0x70, 0x9e, 0x23, 0xcf, 0x46, 0x86,
	0x57, 0xa8, 0x7f, 0x1f, 0x73, 0xc5, 0xac, 0x34, 0x56, 0xd2, 0x51, 0x25, 0xad, 0xe5, 0x28, 0x23,
	0xb1, 0x0d, 0x3f, 0xb4, 0x54, 0x30, 0x69, 0xa8, 0x6f, 0x29, 0x3c, 0xdf, 0xa3, 0x71, 0x5a, 0x46,
	0x6c, 0xb1, 0x4f, 0x18, 0x62, 0x9d, 0x37, 0x70, 0xaa, 0xa9, 0x4f, 0xb4, 0xda, 0x08, 0xdf, 0x91,
	0x6b, 0xb6, 0x4f, 0xa4, 0x8a, 0xec, 0x2c, 0x3b, 0x1f, 0x2d, 0xc6, 0xa2, 0x19, 0xa2, 0xed, 0xb0,
	0x54, 0x3e, 0x40, 0xb1, 0x55, 0x14, 0x1c, 0xdb, 0x80, 0x75, 0xbe, 0x84, 0x63, 0xfd, 0x9f, 0x85,
	0x3d, 0x25, 0x5b, 0xf9, 0xc5, 0x2b, 0xc0, 0x6d, 0x7b, 0x73, 0x87, 0x7e, 0x4d, 0x1d, 0xe6, 0x06,
	0x8a, 0x80, 0x71, 0xd0, 0xcd, 0x0b, 0xb1, 0x63, 0xe3, 0xd9, 0x54, 0xec, 0x1a, 0xb1, 0x9c, 0xbf,
	0x7d, 0x7c, 0xbe, 0x1f, 0x8c, 0xcb, 0x93, 0x6a, 0x5d, 0x57, 0x01, 0xe3, 0xdf, 0x7f, 0x57, 0xd9,
	0xc5, 0x72, 0x0a, 0x93, 0x8e, 0x8d, 0x78, 0x49, 0xd8, 0x53, 0x12, 0xca, 0xbb, 0x4e, 0xa1, 0x45,
	0x2f, 0x23, 0x3e, 0x1e, 0x6e, 0xee, 0x7c, 0xf9, 0x15, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xa1, 0x2f,
	0x43, 0x9f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ORMServiceClient is the client API for ORMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ORMServiceClient interface {
	SetLiquidationRiskConfig(ctx context.Context, in *LiqRiskTemplateRequest1, opts ...grpc.CallOption) (*LiqRiskTemplateResponse1, error)
}

type oRMServiceClient struct {
	cc *grpc.ClientConn
}

func NewORMServiceClient(cc *grpc.ClientConn) ORMServiceClient {
	return &oRMServiceClient{cc}
}

func (c *oRMServiceClient) SetLiquidationRiskConfig(ctx context.Context, in *LiqRiskTemplateRequest1, opts ...grpc.CallOption) (*LiqRiskTemplateResponse1, error) {
	out := new(LiqRiskTemplateResponse1)
	err := c.cc.Invoke(ctx, "/ORMService/setLiquidationRiskConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ORMServiceServer is the server API for ORMService service.
type ORMServiceServer interface {
	SetLiquidationRiskConfig(context.Context, *LiqRiskTemplateRequest1) (*LiqRiskTemplateResponse1, error)
}

// UnimplementedORMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedORMServiceServer struct {
}

func (*UnimplementedORMServiceServer) SetLiquidationRiskConfig(ctx context.Context, req *LiqRiskTemplateRequest1) (*LiqRiskTemplateResponse1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLiquidationRiskConfig not implemented")
}

func RegisterORMServiceServer(s *grpc.Server, srv ORMServiceServer) {
	s.RegisterService(&_ORMService_serviceDesc, srv)
}

func _ORMService_SetLiquidationRiskConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiqRiskTemplateRequest1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ORMServiceServer).SetLiquidationRiskConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ORMService/SetLiquidationRiskConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ORMServiceServer).SetLiquidationRiskConfig(ctx, req.(*LiqRiskTemplateRequest1))
	}
	return interceptor(ctx, in, info, handler)
}

var _ORMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ORMService",
	HandlerType: (*ORMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setLiquidationRiskConfig",
			Handler:    _ORMService_SetLiquidationRiskConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orm.proto",
}
