// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crm.proto

package crm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CRMErrorCode int32

const (
	CRMErrorCode_EFFECTIVE_DATE_EXITS CRMErrorCode = 0
	CRMErrorCode_PARAM_ERROR          CRMErrorCode = 1
)

var CRMErrorCode_name = map[int32]string{
	0: "EFFECTIVE_DATE_EXITS",
	1: "PARAM_ERROR",
}

var CRMErrorCode_value = map[string]int32{
	"EFFECTIVE_DATE_EXITS": 0,
	"PARAM_ERROR":          1,
}

func (x CRMErrorCode) String() string {
	return proto.EnumName(CRMErrorCode_name, int32(x))
}

func (CRMErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1df4794cc6553fc4, []int{0}
}

type LiqRiskTemplateRequest struct {
	LiquidationRiskConfig *LiquidationRiskConfig `protobuf:"bytes,1,opt,name=liquidationRiskConfig,proto3" json:"liquidationRiskConfig,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *LiqRiskTemplateRequest) Reset()         { *m = LiqRiskTemplateRequest{} }
func (m *LiqRiskTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*LiqRiskTemplateRequest) ProtoMessage()    {}
func (*LiqRiskTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df4794cc6553fc4, []int{0}
}

func (m *LiqRiskTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiqRiskTemplateRequest.Unmarshal(m, b)
}
func (m *LiqRiskTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiqRiskTemplateRequest.Marshal(b, m, deterministic)
}
func (m *LiqRiskTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiqRiskTemplateRequest.Merge(m, src)
}
func (m *LiqRiskTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_LiqRiskTemplateRequest.Size(m)
}
func (m *LiqRiskTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LiqRiskTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LiqRiskTemplateRequest proto.InternalMessageInfo

func (m *LiqRiskTemplateRequest) GetLiquidationRiskConfig() *LiquidationRiskConfig {
	if m != nil {
		return m.LiquidationRiskConfig
	}
	return nil
}

type LiqRiskTemplateResponse struct {
	LiqRiskTemplates     *LiquidationRiskConfig `protobuf:"bytes,1,opt,name=liqRiskTemplates,proto3" json:"liqRiskTemplates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LiqRiskTemplateResponse) Reset()         { *m = LiqRiskTemplateResponse{} }
func (m *LiqRiskTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*LiqRiskTemplateResponse) ProtoMessage()    {}
func (*LiqRiskTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df4794cc6553fc4, []int{1}
}

func (m *LiqRiskTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiqRiskTemplateResponse.Unmarshal(m, b)
}
func (m *LiqRiskTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiqRiskTemplateResponse.Marshal(b, m, deterministic)
}
func (m *LiqRiskTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiqRiskTemplateResponse.Merge(m, src)
}
func (m *LiqRiskTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_LiqRiskTemplateResponse.Size(m)
}
func (m *LiqRiskTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LiqRiskTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LiqRiskTemplateResponse proto.InternalMessageInfo

func (m *LiqRiskTemplateResponse) GetLiqRiskTemplates() *LiquidationRiskConfig {
	if m != nil {
		return m.LiqRiskTemplates
	}
	return nil
}

type LiqRiskTemplateListResponse struct {
	LiqRiskTemplates     []*LiquidationRiskConfig `protobuf:"bytes,1,rep,name=liqRiskTemplates,proto3" json:"liqRiskTemplates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *LiqRiskTemplateListResponse) Reset()         { *m = LiqRiskTemplateListResponse{} }
func (m *LiqRiskTemplateListResponse) String() string { return proto.CompactTextString(m) }
func (*LiqRiskTemplateListResponse) ProtoMessage()    {}
func (*LiqRiskTemplateListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df4794cc6553fc4, []int{2}
}

func (m *LiqRiskTemplateListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiqRiskTemplateListResponse.Unmarshal(m, b)
}
func (m *LiqRiskTemplateListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiqRiskTemplateListResponse.Marshal(b, m, deterministic)
}
func (m *LiqRiskTemplateListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiqRiskTemplateListResponse.Merge(m, src)
}
func (m *LiqRiskTemplateListResponse) XXX_Size() int {
	return xxx_messageInfo_LiqRiskTemplateListResponse.Size(m)
}
func (m *LiqRiskTemplateListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LiqRiskTemplateListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LiqRiskTemplateListResponse proto.InternalMessageInfo

func (m *LiqRiskTemplateListResponse) GetLiqRiskTemplates() []*LiquidationRiskConfig {
	if m != nil {
		return m.LiqRiskTemplates
	}
	return nil
}

type LiquidationOrderRequest struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LiquidationOrderId   int64    `protobuf:"varint,4,opt,name=liquidationOrderId,proto3" json:"liquidationOrderId,omitempty"`
	Page                 *Page    `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiquidationOrderRequest) Reset()         { *m = LiquidationOrderRequest{} }
func (m *LiquidationOrderRequest) String() string { return proto.CompactTextString(m) }
func (*LiquidationOrderRequest) ProtoMessage()    {}
func (*LiquidationOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df4794cc6553fc4, []int{3}
}

func (m *LiquidationOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidationOrderRequest.Unmarshal(m, b)
}
func (m *LiquidationOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidationOrderRequest.Marshal(b, m, deterministic)
}
func (m *LiquidationOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationOrderRequest.Merge(m, src)
}
func (m *LiquidationOrderRequest) XXX_Size() int {
	return xxx_messageInfo_LiquidationOrderRequest.Size(m)
}
func (m *LiquidationOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationOrderRequest proto.InternalMessageInfo

func (m *LiquidationOrderRequest) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *LiquidationOrderRequest) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *LiquidationOrderRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LiquidationOrderRequest) GetLiquidationOrderId() int64 {
	if m != nil {
		return m.LiquidationOrderId
	}
	return 0
}

func (m *LiquidationOrderRequest) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type LiquidationOrdersResponse struct {
	Orders               []*LiquidationOrder `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalCount           int32               `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	PageCount            int32               `protobuf:"varint,3,opt,name=pageCount,proto3" json:"pageCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LiquidationOrdersResponse) Reset()         { *m = LiquidationOrdersResponse{} }
func (m *LiquidationOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*LiquidationOrdersResponse) ProtoMessage()    {}
func (*LiquidationOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df4794cc6553fc4, []int{4}
}

func (m *LiquidationOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidationOrdersResponse.Unmarshal(m, b)
}
func (m *LiquidationOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidationOrdersResponse.Marshal(b, m, deterministic)
}
func (m *LiquidationOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationOrdersResponse.Merge(m, src)
}
func (m *LiquidationOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_LiquidationOrdersResponse.Size(m)
}
func (m *LiquidationOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationOrdersResponse proto.InternalMessageInfo

func (m *LiquidationOrdersResponse) GetOrders() []*LiquidationOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *LiquidationOrdersResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *LiquidationOrdersResponse) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type LiqWarningAccountRequest struct {
	Page                 *Page    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiqWarningAccountRequest) Reset()         { *m = LiqWarningAccountRequest{} }
func (m *LiqWarningAccountRequest) String() string { return proto.CompactTextString(m) }
func (*LiqWarningAccountRequest) ProtoMessage()    {}
func (*LiqWarningAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df4794cc6553fc4, []int{5}
}

func (m *LiqWarningAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiqWarningAccountRequest.Unmarshal(m, b)
}
func (m *LiqWarningAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiqWarningAccountRequest.Marshal(b, m, deterministic)
}
func (m *LiqWarningAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiqWarningAccountRequest.Merge(m, src)
}
func (m *LiqWarningAccountRequest) XXX_Size() int {
	return xxx_messageInfo_LiqWarningAccountRequest.Size(m)
}
func (m *LiqWarningAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LiqWarningAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LiqWarningAccountRequest proto.InternalMessageInfo

func (m *LiqWarningAccountRequest) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type LiqWarningAccountsResponse struct {
	Assets               []*Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	TotalCount           int32    `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	PageCount            int32    `protobuf:"varint,3,opt,name=pageCount,proto3" json:"pageCount,omitempty"`
	PageNum              int32    `protobuf:"varint,4,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiqWarningAccountsResponse) Reset()         { *m = LiqWarningAccountsResponse{} }
func (m *LiqWarningAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*LiqWarningAccountsResponse) ProtoMessage()    {}
func (*LiqWarningAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df4794cc6553fc4, []int{6}
}

func (m *LiqWarningAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiqWarningAccountsResponse.Unmarshal(m, b)
}
func (m *LiqWarningAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiqWarningAccountsResponse.Marshal(b, m, deterministic)
}
func (m *LiqWarningAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiqWarningAccountsResponse.Merge(m, src)
}
func (m *LiqWarningAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_LiqWarningAccountsResponse.Size(m)
}
func (m *LiqWarningAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LiqWarningAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LiqWarningAccountsResponse proto.InternalMessageInfo

func (m *LiqWarningAccountsResponse) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *LiqWarningAccountsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *LiqWarningAccountsResponse) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

func (m *LiqWarningAccountsResponse) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func init() {
	proto.RegisterEnum("CRMErrorCode", CRMErrorCode_name, CRMErrorCode_value)
	proto.RegisterType((*LiqRiskTemplateRequest)(nil), "LiqRiskTemplateRequest")
	proto.RegisterType((*LiqRiskTemplateResponse)(nil), "LiqRiskTemplateResponse")
	proto.RegisterType((*LiqRiskTemplateListResponse)(nil), "LiqRiskTemplateListResponse")
	proto.RegisterType((*LiquidationOrderRequest)(nil), "LiquidationOrderRequest")
	proto.RegisterType((*LiquidationOrdersResponse)(nil), "LiquidationOrdersResponse")
	proto.RegisterType((*LiqWarningAccountRequest)(nil), "LiqWarningAccountRequest")
	proto.RegisterType((*LiqWarningAccountsResponse)(nil), "LiqWarningAccountsResponse")
}

func init() { proto.RegisterFile("crm.proto", fileDescriptor_1df4794cc6553fc4) }

var fileDescriptor_1df4794cc6553fc4 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0x9b, 0x26, 0xbf, 0x3a, 0xfd, 0x25, 0xc2, 0x8a, 0xb6, 0x9b, 0xb4, 0x2a, 0x95, 0x4f,
	0xa5, 0x87, 0x8d, 0x28, 0xe2, 0x00, 0xb7, 0x34, 0xb8, 0x52, 0xa4, 0x94, 0x54, 0xdb, 0x08, 0xb8,
	0xa0, 0x6a, 0x89, 0xb7, 0xd6, 0xaa, 0xb6, 0xd7, 0xde, 0x5d, 0x57, 0x70, 0x45, 0xbc, 0x01, 0x3c,
	0x09, 0xaf, 0xc2, 0x2b, 0xf0, 0x16, 0x5c, 0x90, 0x37, 0x36, 0xa1, 0x89, 0x4d, 0x85, 0x38, 0xce,
	0x37, 0xb3, 0xf3, 0x7d, 0xf3, 0x79, 0xc6, 0xb0, 0x31, 0x53, 0x11, 0x49, 0x94, 0x34, 0xb2, 0xb7,
	0x19, 0x49, 0x9f, 0x87, 0x45, 0xb0, 0x17, 0x48, 0x19, 0x84, 0xbc, 0xcf, 0x12, 0xd1, 0x67, 0x71,
	0x2c, 0x0d, 0x33, 0x42, 0xc6, 0x7a, 0x9e, 0x75, 0xaf, 0x60, 0x7b, 0x2c, 0x52, 0x2a, 0xf4, 0xf5,
	0x94, 0x47, 0x49, 0xc8, 0x0c, 0xa7, 0x3c, 0xcd, 0xb8, 0x36, 0x68, 0x0c, 0x5b, 0xa1, 0x48, 0x33,
	0xe1, 0xdb, 0xfa, 0xbc, 0x62, 0x28, 0xe3, 0x2b, 0x11, 0x60, 0xe7, 0xc0, 0x39, 0xdc, 0x3c, 0xde,
	0x26, 0xe3, 0xaa, 0x2c, 0xad, 0x7e, 0xe4, 0xbe, 0x85, 0x9d, 0x15, 0x1e, 0x9d, 0xc8, 0x58, 0x73,
	0x74, 0x02, 0x9d, 0xf0, 0x76, 0x4a, 0xdf, 0xc1, 0xb1, 0x52, 0xef, 0x32, 0xd8, 0x5d, 0x6a, 0x3f,
	0x16, 0xda, 0xdc, 0x41, 0xd1, 0xfc, 0x2b, 0x8a, 0xaf, 0x8e, 0x1d, 0xa1, 0xac, 0x9d, 0x28, 0x9f,
	0xab, 0xd2, 0xab, 0x3d, 0xd8, 0x60, 0xb3, 0x99, 0xcc, 0x62, 0x33, 0xf2, 0xad, 0xf6, 0x26, 0x5d,
	0x00, 0x68, 0x1b, 0xda, 0x11, 0x53, 0xd7, 0xdc, 0xe0, 0xb5, 0x03, 0xe7, 0x70, 0x83, 0x16, 0x51,
	0x8e, 0x6b, 0xc3, 0x4c, 0xa6, 0x71, 0x73, 0x8e, 0xcf, 0x23, 0x44, 0x00, 0x85, 0x4b, 0x44, 0x23,
	0x1f, 0xaf, 0xdb, 0xb6, 0x15, 0x19, 0xd4, 0x85, 0xf5, 0x84, 0x05, 0x1c, 0xb7, 0xac, 0x69, 0x2d,
	0x72, 0xce, 0x02, 0x4e, 0x2d, 0xe4, 0x7e, 0x72, 0xa0, 0xbb, 0x2c, 0x5a, 0xff, 0xb2, 0xe5, 0x11,
	0xb4, 0xa5, 0x45, 0x0a, 0x33, 0xee, 0x93, 0x95, 0x01, 0x8b, 0x02, 0xb4, 0x0f, 0x60, 0xa4, 0x61,
	0xe1, 0x30, 0x9f, 0xc9, 0xce, 0xd1, 0xa2, 0xbf, 0x21, 0xb9, 0x03, 0x39, 0xe1, 0x3c, 0xdd, 0xb4,
	0xe9, 0x05, 0xe0, 0x3e, 0x05, 0x3c, 0x16, 0xe9, 0x6b, 0xa6, 0x62, 0x11, 0x07, 0x83, 0xb9, 0x31,
	0xa5, 0x77, 0xa5, 0x7a, 0x67, 0x55, 0xfd, 0x17, 0x07, 0x7a, 0x2b, 0xef, 0x16, 0xf2, 0xf7, 0xa1,
	0xcd, 0xb4, 0xe6, 0xa6, 0x94, 0xdf, 0x26, 0x83, 0x3c, 0xa4, 0x05, 0xfa, 0x6f, 0x9a, 0x11, 0x86,
	0xff, 0xf2, 0xe0, 0x65, 0x16, 0x59, 0xeb, 0x5b, 0xb4, 0x0c, 0x8f, 0x9e, 0xc1, 0xff, 0x43, 0x7a,
	0xe6, 0x29, 0x25, 0xd5, 0x50, 0xfa, 0x1c, 0x61, 0x78, 0xe0, 0x9d, 0x9e, 0x7a, 0xc3, 0xe9, 0xe8,
	0x95, 0x77, 0xf9, 0x62, 0x30, 0xf5, 0x2e, 0xbd, 0x37, 0xa3, 0xe9, 0x45, 0xa7, 0x81, 0xee, 0xc1,
	0xe6, 0xf9, 0x80, 0x0e, 0xce, 0x2e, 0x3d, 0x4a, 0x27, 0xb4, 0xe3, 0x1c, 0xff, 0x58, 0x03, 0x18,
	0xd2, 0xb3, 0x0b, 0xae, 0x6e, 0xc4, 0x8c, 0xa3, 0x09, 0x60, 0xcd, 0x4d, 0xe5, 0x06, 0xa2, 0x1d,
	0x52, 0x7d, 0x98, 0x3d, 0x4c, 0x6a, 0x2e, 0xc9, 0x6d, 0xa0, 0x0b, 0xc0, 0x69, 0xc6, 0xd5, 0x87,
	0x8a, 0x63, 0xa8, 0x6f, 0xb8, 0x47, 0xfe, 0x70, 0x3b, 0x6e, 0x03, 0x4d, 0x60, 0xab, 0x6c, 0x7a,
	0x6b, 0x39, 0x10, 0x26, 0x35, 0x07, 0xd1, 0xeb, 0x91, 0xda, 0xad, 0x73, 0x1b, 0xe8, 0x06, 0x1e,
	0x2e, 0x37, 0x5c, 0xfa, 0xc6, 0xa8, 0x4b, 0xea, 0x16, 0xa6, 0xb7, 0x4b, 0xea, 0x77, 0xc2, 0xdd,
	0xfd, 0xf8, 0xed, 0xfb, 0xe7, 0xb5, 0x2d, 0xb7, 0xd3, 0xbf, 0x79, 0xdc, 0xb7, 0x24, 0x45, 0xc9,
	0x73, 0xe7, 0xe8, 0xa4, 0x0b, 0x3b, 0x33, 0x19, 0x91, 0xf7, 0x19, 0x4f, 0x45, 0x46, 0x02, 0x95,
	0xcc, 0x02, 0x1e, 0x73, 0xc5, 0x0c, 0x7f, 0xd7, 0xb6, 0xbf, 0xc3, 0x27, 0x3f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x45, 0x26, 0xe6, 0x2d, 0x46, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CRMServiceClient is the client API for CRMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CRMServiceClient interface {
	SetLiquidationRiskConfig(ctx context.Context, in *LiqRiskTemplateRequest, opts ...grpc.CallOption) (*LiqRiskTemplateResponse, error)
	QueryLiqRiskTemplateList(ctx context.Context, in *LiqRiskTemplateRequest, opts ...grpc.CallOption) (*LiqRiskTemplateListResponse, error)
	QueryLiquidationOrder(ctx context.Context, in *LiquidationOrderRequest, opts ...grpc.CallOption) (*LiquidationOrdersResponse, error)
	QueryLiquidationWarningAccounts(ctx context.Context, in *LiqWarningAccountRequest, opts ...grpc.CallOption) (*LiqWarningAccountsResponse, error)
}

type cRMServiceClient struct {
	cc *grpc.ClientConn
}

func NewCRMServiceClient(cc *grpc.ClientConn) CRMServiceClient {
	return &cRMServiceClient{cc}
}

func (c *cRMServiceClient) SetLiquidationRiskConfig(ctx context.Context, in *LiqRiskTemplateRequest, opts ...grpc.CallOption) (*LiqRiskTemplateResponse, error) {
	out := new(LiqRiskTemplateResponse)
	err := c.cc.Invoke(ctx, "/CRMService/setLiquidationRiskConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRMServiceClient) QueryLiqRiskTemplateList(ctx context.Context, in *LiqRiskTemplateRequest, opts ...grpc.CallOption) (*LiqRiskTemplateListResponse, error) {
	out := new(LiqRiskTemplateListResponse)
	err := c.cc.Invoke(ctx, "/CRMService/queryLiqRiskTemplateList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRMServiceClient) QueryLiquidationOrder(ctx context.Context, in *LiquidationOrderRequest, opts ...grpc.CallOption) (*LiquidationOrdersResponse, error) {
	out := new(LiquidationOrdersResponse)
	err := c.cc.Invoke(ctx, "/CRMService/queryLiquidationOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRMServiceClient) QueryLiquidationWarningAccounts(ctx context.Context, in *LiqWarningAccountRequest, opts ...grpc.CallOption) (*LiqWarningAccountsResponse, error) {
	out := new(LiqWarningAccountsResponse)
	err := c.cc.Invoke(ctx, "/CRMService/queryLiquidationWarningAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRMServiceServer is the server API for CRMService service.
type CRMServiceServer interface {
	SetLiquidationRiskConfig(context.Context, *LiqRiskTemplateRequest) (*LiqRiskTemplateResponse, error)
	QueryLiqRiskTemplateList(context.Context, *LiqRiskTemplateRequest) (*LiqRiskTemplateListResponse, error)
	QueryLiquidationOrder(context.Context, *LiquidationOrderRequest) (*LiquidationOrdersResponse, error)
	QueryLiquidationWarningAccounts(context.Context, *LiqWarningAccountRequest) (*LiqWarningAccountsResponse, error)
}

// UnimplementedCRMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCRMServiceServer struct {
}

func (*UnimplementedCRMServiceServer) SetLiquidationRiskConfig(ctx context.Context, req *LiqRiskTemplateRequest) (*LiqRiskTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLiquidationRiskConfig not implemented")
}
func (*UnimplementedCRMServiceServer) QueryLiqRiskTemplateList(ctx context.Context, req *LiqRiskTemplateRequest) (*LiqRiskTemplateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLiqRiskTemplateList not implemented")
}
func (*UnimplementedCRMServiceServer) QueryLiquidationOrder(ctx context.Context, req *LiquidationOrderRequest) (*LiquidationOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLiquidationOrder not implemented")
}
func (*UnimplementedCRMServiceServer) QueryLiquidationWarningAccounts(ctx context.Context, req *LiqWarningAccountRequest) (*LiqWarningAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLiquidationWarningAccounts not implemented")
}

func RegisterCRMServiceServer(s *grpc.Server, srv CRMServiceServer) {
	s.RegisterService(&_CRMService_serviceDesc, srv)
}

func _CRMService_SetLiquidationRiskConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiqRiskTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRMServiceServer).SetLiquidationRiskConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CRMService/SetLiquidationRiskConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRMServiceServer).SetLiquidationRiskConfig(ctx, req.(*LiqRiskTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRMService_QueryLiqRiskTemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiqRiskTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRMServiceServer).QueryLiqRiskTemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CRMService/QueryLiqRiskTemplateList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRMServiceServer).QueryLiqRiskTemplateList(ctx, req.(*LiqRiskTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRMService_QueryLiquidationOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiquidationOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRMServiceServer).QueryLiquidationOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CRMService/QueryLiquidationOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRMServiceServer).QueryLiquidationOrder(ctx, req.(*LiquidationOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRMService_QueryLiquidationWarningAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiqWarningAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRMServiceServer).QueryLiquidationWarningAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CRMService/QueryLiquidationWarningAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRMServiceServer).QueryLiquidationWarningAccounts(ctx, req.(*LiqWarningAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CRMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CRMService",
	HandlerType: (*CRMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setLiquidationRiskConfig",
			Handler:    _CRMService_SetLiquidationRiskConfig_Handler,
		},
		{
			MethodName: "queryLiqRiskTemplateList",
			Handler:    _CRMService_QueryLiqRiskTemplateList_Handler,
		},
		{
			MethodName: "queryLiquidationOrder",
			Handler:    _CRMService_QueryLiquidationOrder_Handler,
		},
		{
			MethodName: "queryLiquidationWarningAccounts",
			Handler:    _CRMService_QueryLiquidationWarningAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crm.proto",
}
