// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Page struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Page) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Cash struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Settled              float64  `protobuf:"fixed64,3,opt,name=settled,proto3" json:"settled,omitempty"`
	Unsettled            float64  `protobuf:"fixed64,4,opt,name=unsettled,proto3" json:"unsettled,omitempty"`
	Locked               float64  `protobuf:"fixed64,5,opt,name=locked,proto3" json:"locked,omitempty"`
	AccruedDividend      float64  `protobuf:"fixed64,6,opt,name=accruedDividend,proto3" json:"accruedDividend,omitempty"`
	AccruedInterest      float64  `protobuf:"fixed64,7,opt,name=accruedInterest,proto3" json:"accruedInterest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cash) Reset()         { *m = Cash{} }
func (m *Cash) String() string { return proto.CompactTextString(m) }
func (*Cash) ProtoMessage()    {}
func (*Cash) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *Cash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cash.Unmarshal(m, b)
}
func (m *Cash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cash.Marshal(b, m, deterministic)
}
func (m *Cash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cash.Merge(m, src)
}
func (m *Cash) XXX_Size() int {
	return xxx_messageInfo_Cash.Size(m)
}
func (m *Cash) XXX_DiscardUnknown() {
	xxx_messageInfo_Cash.DiscardUnknown(m)
}

var xxx_messageInfo_Cash proto.InternalMessageInfo

func (m *Cash) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Cash) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Cash) GetSettled() float64 {
	if m != nil {
		return m.Settled
	}
	return 0
}

func (m *Cash) GetUnsettled() float64 {
	if m != nil {
		return m.Unsettled
	}
	return 0
}

func (m *Cash) GetLocked() float64 {
	if m != nil {
		return m.Locked
	}
	return 0
}

func (m *Cash) GetAccruedDividend() float64 {
	if m != nil {
		return m.AccruedDividend
	}
	return 0
}

func (m *Cash) GetAccruedInterest() float64 {
	if m != nil {
		return m.AccruedInterest
	}
	return 0
}

type Position struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	SecurityType         string   `protobuf:"bytes,2,opt,name=securityType,proto3" json:"securityType,omitempty"`
	SecurityId           int64    `protobuf:"varint,3,opt,name=securityId,proto3" json:"securityId,omitempty"`
	TotalQuantity        float64  `protobuf:"fixed64,4,opt,name=totalQuantity,proto3" json:"totalQuantity,omitempty"`
	UnsettledQuantity    float64  `protobuf:"fixed64,5,opt,name=unsettledQuantity,proto3" json:"unsettledQuantity,omitempty"`
	LockedQuantity       float64  `protobuf:"fixed64,6,opt,name=lockedQuantity,proto3" json:"lockedQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Position) GetSecurityType() string {
	if m != nil {
		return m.SecurityType
	}
	return ""
}

func (m *Position) GetSecurityId() int64 {
	if m != nil {
		return m.SecurityId
	}
	return 0
}

func (m *Position) GetTotalQuantity() float64 {
	if m != nil {
		return m.TotalQuantity
	}
	return 0
}

func (m *Position) GetUnsettledQuantity() float64 {
	if m != nil {
		return m.UnsettledQuantity
	}
	return 0
}

func (m *Position) GetLockedQuantity() float64 {
	if m != nil {
		return m.LockedQuantity
	}
	return 0
}

type Asset struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	EquityWithLoan       float64  `protobuf:"fixed64,3,opt,name=equityWithLoan,proto3" json:"equityWithLoan,omitempty"`
	RegTEquityWithLoan   float64  `protobuf:"fixed64,4,opt,name=regTEquityWithLoan,proto3" json:"regTEquityWithLoan,omitempty"`
	NetLiquidation       float64  `protobuf:"fixed64,5,opt,name=netLiquidation,proto3" json:"netLiquidation,omitempty"`
	ExcessEquity         float64  `protobuf:"fixed64,6,opt,name=excessEquity,proto3" json:"excessEquity,omitempty"`
	ExcessLiquidity      float64  `protobuf:"fixed64,7,opt,name=excessLiquidity,proto3" json:"excessLiquidity,omitempty"`
	OvernightLiquidation float64  `protobuf:"fixed64,8,opt,name=overnightLiquidation,proto3" json:"overnightLiquidation,omitempty"`
	AvailableEE          float64  `protobuf:"fixed64,9,opt,name=availableEE,proto3" json:"availableEE,omitempty"`
	BuyingPower          float64  `protobuf:"fixed64,10,opt,name=buyingPower,proto3" json:"buyingPower,omitempty"`
	AvailableBuyingPower float64  `protobuf:"fixed64,11,opt,name=availableBuyingPower,proto3" json:"availableBuyingPower,omitempty"`
	Leverage             float64  `protobuf:"fixed64,12,opt,name=leverage,proto3" json:"leverage,omitempty"`
	CanMargin            int32    `protobuf:"varint,13,opt,name=canMargin,proto3" json:"canMargin,omitempty"`
	InitialMargin        float64  `protobuf:"fixed64,14,opt,name=initialMargin,proto3" json:"initialMargin,omitempty"`
	MaintenanceMargin    float64  `protobuf:"fixed64,15,opt,name=maintenanceMargin,proto3" json:"maintenanceMargin,omitempty"`
	CashBalance          float64  `protobuf:"fixed64,16,opt,name=cashBalance,proto3" json:"cashBalance,omitempty"`
	AccountType          string   `protobuf:"bytes,17,opt,name=accountType,proto3" json:"accountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Asset) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Asset) GetEquityWithLoan() float64 {
	if m != nil {
		return m.EquityWithLoan
	}
	return 0
}

func (m *Asset) GetRegTEquityWithLoan() float64 {
	if m != nil {
		return m.RegTEquityWithLoan
	}
	return 0
}

func (m *Asset) GetNetLiquidation() float64 {
	if m != nil {
		return m.NetLiquidation
	}
	return 0
}

func (m *Asset) GetExcessEquity() float64 {
	if m != nil {
		return m.ExcessEquity
	}
	return 0
}

func (m *Asset) GetExcessLiquidity() float64 {
	if m != nil {
		return m.ExcessLiquidity
	}
	return 0
}

func (m *Asset) GetOvernightLiquidation() float64 {
	if m != nil {
		return m.OvernightLiquidation
	}
	return 0
}

func (m *Asset) GetAvailableEE() float64 {
	if m != nil {
		return m.AvailableEE
	}
	return 0
}

func (m *Asset) GetBuyingPower() float64 {
	if m != nil {
		return m.BuyingPower
	}
	return 0
}

func (m *Asset) GetAvailableBuyingPower() float64 {
	if m != nil {
		return m.AvailableBuyingPower
	}
	return 0
}

func (m *Asset) GetLeverage() float64 {
	if m != nil {
		return m.Leverage
	}
	return 0
}

func (m *Asset) GetCanMargin() int32 {
	if m != nil {
		return m.CanMargin
	}
	return 0
}

func (m *Asset) GetInitialMargin() float64 {
	if m != nil {
		return m.InitialMargin
	}
	return 0
}

func (m *Asset) GetMaintenanceMargin() float64 {
	if m != nil {
		return m.MaintenanceMargin
	}
	return 0
}

func (m *Asset) GetCashBalance() float64 {
	if m != nil {
		return m.CashBalance
	}
	return 0
}

func (m *Asset) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

type CashActivity struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	CashType             string   `protobuf:"bytes,3,opt,name=cashType,proto3" json:"cashType,omitempty"`
	CashActivityId       int64    `protobuf:"varint,4,opt,name=cashActivityId,proto3" json:"cashActivityId,omitempty"`
	Amount               float64  `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Desc                 string   `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	HappenAt             uint64   `protobuf:"varint,7,opt,name=happenAt,proto3" json:"happenAt,omitempty"`
	SettleAt             uint64   `protobuf:"varint,8,opt,name=settleAt,proto3" json:"settleAt,omitempty"`
	CreateAt             uint64   `protobuf:"varint,9,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             uint64   `protobuf:"varint,10,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CashActivity) Reset()         { *m = CashActivity{} }
func (m *CashActivity) String() string { return proto.CompactTextString(m) }
func (*CashActivity) ProtoMessage()    {}
func (*CashActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *CashActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CashActivity.Unmarshal(m, b)
}
func (m *CashActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CashActivity.Marshal(b, m, deterministic)
}
func (m *CashActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CashActivity.Merge(m, src)
}
func (m *CashActivity) XXX_Size() int {
	return xxx_messageInfo_CashActivity.Size(m)
}
func (m *CashActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_CashActivity.DiscardUnknown(m)
}

var xxx_messageInfo_CashActivity proto.InternalMessageInfo

func (m *CashActivity) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *CashActivity) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CashActivity) GetCashType() string {
	if m != nil {
		return m.CashType
	}
	return ""
}

func (m *CashActivity) GetCashActivityId() int64 {
	if m != nil {
		return m.CashActivityId
	}
	return 0
}

func (m *CashActivity) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CashActivity) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CashActivity) GetHappenAt() uint64 {
	if m != nil {
		return m.HappenAt
	}
	return 0
}

func (m *CashActivity) GetSettleAt() uint64 {
	if m != nil {
		return m.SettleAt
	}
	return 0
}

func (m *CashActivity) GetCreateAt() uint64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *CashActivity) GetUpdateAt() uint64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type MarginRate struct {
	Id                     int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SecurityId             int64    `protobuf:"varint,2,opt,name=securityId,proto3" json:"securityId,omitempty"`
	Symbol                 string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Market                 string   `protobuf:"bytes,4,opt,name=market,proto3" json:"market,omitempty"`
	LongInitialMargin      float64  `protobuf:"fixed64,5,opt,name=longInitialMargin,proto3" json:"longInitialMargin,omitempty"`
	LongOvernightMargin    float64  `protobuf:"fixed64,6,opt,name=longOvernightMargin,proto3" json:"longOvernightMargin,omitempty"`
	LongMaintenanceMargin  float64  `protobuf:"fixed64,7,opt,name=longMaintenanceMargin,proto3" json:"longMaintenanceMargin,omitempty"`
	ShortInitialMargin     float64  `protobuf:"fixed64,8,opt,name=shortInitialMargin,proto3" json:"shortInitialMargin,omitempty"`
	ShortMaintenanceMargin float64  `protobuf:"fixed64,9,opt,name=shortMaintenanceMargin,proto3" json:"shortMaintenanceMargin,omitempty"`
	ShortOvernightMargin   float64  `protobuf:"fixed64,10,opt,name=shortOvernightMargin,proto3" json:"shortOvernightMargin,omitempty"`
	ShortFeeRate           float64  `protobuf:"fixed64,11,opt,name=shortFeeRate,proto3" json:"shortFeeRate,omitempty"`
	ShortAvailable         int64    `protobuf:"varint,12,opt,name=shortAvailable,proto3" json:"shortAvailable,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *MarginRate) Reset()         { *m = MarginRate{} }
func (m *MarginRate) String() string { return proto.CompactTextString(m) }
func (*MarginRate) ProtoMessage()    {}
func (*MarginRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *MarginRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarginRate.Unmarshal(m, b)
}
func (m *MarginRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarginRate.Marshal(b, m, deterministic)
}
func (m *MarginRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarginRate.Merge(m, src)
}
func (m *MarginRate) XXX_Size() int {
	return xxx_messageInfo_MarginRate.Size(m)
}
func (m *MarginRate) XXX_DiscardUnknown() {
	xxx_messageInfo_MarginRate.DiscardUnknown(m)
}

var xxx_messageInfo_MarginRate proto.InternalMessageInfo

func (m *MarginRate) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MarginRate) GetSecurityId() int64 {
	if m != nil {
		return m.SecurityId
	}
	return 0
}

func (m *MarginRate) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MarginRate) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *MarginRate) GetLongInitialMargin() float64 {
	if m != nil {
		return m.LongInitialMargin
	}
	return 0
}

func (m *MarginRate) GetLongOvernightMargin() float64 {
	if m != nil {
		return m.LongOvernightMargin
	}
	return 0
}

func (m *MarginRate) GetLongMaintenanceMargin() float64 {
	if m != nil {
		return m.LongMaintenanceMargin
	}
	return 0
}

func (m *MarginRate) GetShortInitialMargin() float64 {
	if m != nil {
		return m.ShortInitialMargin
	}
	return 0
}

func (m *MarginRate) GetShortMaintenanceMargin() float64 {
	if m != nil {
		return m.ShortMaintenanceMargin
	}
	return 0
}

func (m *MarginRate) GetShortOvernightMargin() float64 {
	if m != nil {
		return m.ShortOvernightMargin
	}
	return 0
}

func (m *MarginRate) GetShortFeeRate() float64 {
	if m != nil {
		return m.ShortFeeRate
	}
	return 0
}

func (m *MarginRate) GetShortAvailable() int64 {
	if m != nil {
		return m.ShortAvailable
	}
	return 0
}

type LiquidationOrder struct {
	LiqOrderId           int64    `protobuf:"varint,1,opt,name=liqOrderId,proto3" json:"liqOrderId,omitempty"`
	SecurityId           int64    `protobuf:"varint,2,opt,name=securityId,proto3" json:"securityId,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Market               string   `protobuf:"bytes,4,opt,name=market,proto3" json:"market,omitempty"`
	Currency             string   `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	LiquidationType      string   `protobuf:"bytes,6,opt,name=liquidationType,proto3" json:"liquidationType,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Quantity             float64  `protobuf:"fixed64,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float64  `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiquidationOrder) Reset()         { *m = LiquidationOrder{} }
func (m *LiquidationOrder) String() string { return proto.CompactTextString(m) }
func (*LiquidationOrder) ProtoMessage()    {}
func (*LiquidationOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *LiquidationOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidationOrder.Unmarshal(m, b)
}
func (m *LiquidationOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidationOrder.Marshal(b, m, deterministic)
}
func (m *LiquidationOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationOrder.Merge(m, src)
}
func (m *LiquidationOrder) XXX_Size() int {
	return xxx_messageInfo_LiquidationOrder.Size(m)
}
func (m *LiquidationOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationOrder.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationOrder proto.InternalMessageInfo

func (m *LiquidationOrder) GetLiqOrderId() int64 {
	if m != nil {
		return m.LiqOrderId
	}
	return 0
}

func (m *LiquidationOrder) GetSecurityId() int64 {
	if m != nil {
		return m.SecurityId
	}
	return 0
}

func (m *LiquidationOrder) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *LiquidationOrder) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *LiquidationOrder) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *LiquidationOrder) GetLiquidationType() string {
	if m != nil {
		return m.LiquidationType
	}
	return ""
}

func (m *LiquidationOrder) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LiquidationOrder) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *LiquidationOrder) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *LiquidationOrder) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *LiquidationOrder) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type LiquidationRiskConfig struct {
	LiquidationRiskTemplateId int32    `protobuf:"varint,1,opt,name=liquidationRiskTemplateId,proto3" json:"liquidationRiskTemplateId,omitempty"`
	TemplateName              string   `protobuf:"bytes,2,opt,name=templateName,proto3" json:"templateName,omitempty"`
	AutoLiquidation           string   `protobuf:"bytes,3,opt,name=autoLiquidation,proto3" json:"autoLiquidation,omitempty"`
	Sem                       string   `protobuf:"bytes,4,opt,name=sem,proto3" json:"sem,omitempty"`
	SemRate                   float64  `protobuf:"fixed64,5,opt,name=semRate,proto3" json:"semRate,omitempty"`
	EodRate                   float64  `protobuf:"fixed64,6,opt,name=eodRate,proto3" json:"eodRate,omitempty"`
	WaringELRate              float64  `protobuf:"fixed64,7,opt,name=waringELRate,proto3" json:"waringELRate,omitempty"`
	UpdatedAt                 float64  `protobuf:"fixed64,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Status                    string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	EffectiveDate             string   `protobuf:"bytes,10,opt,name=effectiveDate,proto3" json:"effectiveDate,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *LiquidationRiskConfig) Reset()         { *m = LiquidationRiskConfig{} }
func (m *LiquidationRiskConfig) String() string { return proto.CompactTextString(m) }
func (*LiquidationRiskConfig) ProtoMessage()    {}
func (*LiquidationRiskConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}

func (m *LiquidationRiskConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidationRiskConfig.Unmarshal(m, b)
}
func (m *LiquidationRiskConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidationRiskConfig.Marshal(b, m, deterministic)
}
func (m *LiquidationRiskConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidationRiskConfig.Merge(m, src)
}
func (m *LiquidationRiskConfig) XXX_Size() int {
	return xxx_messageInfo_LiquidationRiskConfig.Size(m)
}
func (m *LiquidationRiskConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidationRiskConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidationRiskConfig proto.InternalMessageInfo

func (m *LiquidationRiskConfig) GetLiquidationRiskTemplateId() int32 {
	if m != nil {
		return m.LiquidationRiskTemplateId
	}
	return 0
}

func (m *LiquidationRiskConfig) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *LiquidationRiskConfig) GetAutoLiquidation() string {
	if m != nil {
		return m.AutoLiquidation
	}
	return ""
}

func (m *LiquidationRiskConfig) GetSem() string {
	if m != nil {
		return m.Sem
	}
	return ""
}

func (m *LiquidationRiskConfig) GetSemRate() float64 {
	if m != nil {
		return m.SemRate
	}
	return 0
}

func (m *LiquidationRiskConfig) GetEodRate() float64 {
	if m != nil {
		return m.EodRate
	}
	return 0
}

func (m *LiquidationRiskConfig) GetWaringELRate() float64 {
	if m != nil {
		return m.WaringELRate
	}
	return 0
}

func (m *LiquidationRiskConfig) GetUpdatedAt() float64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *LiquidationRiskConfig) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LiquidationRiskConfig) GetEffectiveDate() string {
	if m != nil {
		return m.EffectiveDate
	}
	return ""
}

func init() {
	proto.RegisterType((*Page)(nil), "Page")
	proto.RegisterType((*Cash)(nil), "Cash")
	proto.RegisterType((*Position)(nil), "Position")
	proto.RegisterType((*Asset)(nil), "Asset")
	proto.RegisterType((*CashActivity)(nil), "CashActivity")
	proto.RegisterType((*MarginRate)(nil), "MarginRate")
	proto.RegisterType((*LiquidationOrder)(nil), "LiquidationOrder")
	proto.RegisterType((*LiquidationRiskConfig)(nil), "LiquidationRiskConfig")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 997 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xd6, 0xfe, 0xa5, 0xd9, 0x93, 0xe6, 0xa7, 0x43, 0x1b, 0x5c, 0x84, 0x50, 0xb4, 0xaa, 0xaa,
	0x5c, 0xa0, 0x08, 0x15, 0xc4, 0x15, 0x37, 0x49, 0x1b, 0xa4, 0x95, 0x52, 0x1a, 0xac, 0x48, 0x5c,
	0xcf, 0xda, 0x27, 0xde, 0x51, 0xec, 0xf1, 0xee, 0x78, 0xbc, 0xed, 0xf2, 0x0e, 0xbc, 0x07, 0x4f,
	0xc3, 0x53, 0x70, 0x01, 0x3c, 0x05, 0x3a, 0x67, 0xc6, 0x5e, 0xdb, 0xbb, 0x15, 0x12, 0x70, 0xe7,
	0xef, 0xfb, 0x8e, 0x3d, 0x33, 0xe7, 0x9c, 0xef, 0x78, 0xe0, 0x20, 0xcb, 0x63, 0x4c, 0x2f, 0x16,
	0x26, 0xb7, 0xf9, 0xe4, 0x15, 0x0c, 0x6f, 0x65, 0x82, 0xe2, 0x14, 0xf6, 0x74, 0x99, 0xcd, 0xd0,
	0x04, 0xbd, 0xb3, 0xde, 0xf9, 0x28, 0xf4, 0x48, 0x08, 0x18, 0x16, 0xea, 0x67, 0x0c, 0xfa, 0xcc,
	0xf2, 0xf3, 0xe4, 0xf7, 0x1e, 0x0c, 0x5f, 0xcb, 0x62, 0x2e, 0x3e, 0x87, 0xb1, 0x8c, 0xa2, 0xbc,
	0xd4, 0x76, 0x1a, 0xf3, 0x7b, 0x83, 0x70, 0x43, 0x88, 0xcf, 0x60, 0x3f, 0x2a, 0x8d, 0x41, 0x1d,
	0xad, 0xf9, 0xf5, 0x71, 0x58, 0x63, 0x11, 0xc0, 0xa3, 0x02, 0xad, 0x4d, 0x31, 0x0e, 0x06, 0x67,
	0xbd, 0xf3, 0x5e, 0x58, 0x41, 0xfa, 0x66, 0xa9, 0x2b, 0x6d, 0xc8, 0xda, 0x86, 0xa0, 0x6d, 0xa6,
	0x79, 0xf4, 0x80, 0x71, 0x30, 0x62, 0xc9, 0x23, 0x71, 0x0e, 0xc7, 0x32, 0x8a, 0x4c, 0x89, 0xf1,
	0x1b, 0xb5, 0x52, 0x31, 0xea, 0x38, 0xd8, 0xe3, 0x80, 0x2e, 0xdd, 0x88, 0x9c, 0x6a, 0x8b, 0x06,
	0x0b, 0x1b, 0x3c, 0x6a, 0x45, 0x56, 0xf4, 0xe4, 0x8f, 0x1e, 0xec, 0xdf, 0xe6, 0x85, 0xb2, 0x2a,
	0xd7, 0xff, 0x70, 0xd4, 0x09, 0x3c, 0x2e, 0x30, 0x2a, 0x8d, 0xb2, 0xeb, 0xbb, 0xf5, 0x02, 0xfd,
	0x71, 0x5b, 0x9c, 0xf8, 0x02, 0xa0, 0xc2, 0x53, 0x77, 0xea, 0x41, 0xd8, 0x60, 0xc4, 0x0b, 0x38,
	0xb4, 0xb9, 0x95, 0xe9, 0x8f, 0xa5, 0xd4, 0x56, 0xd9, 0xb5, 0x3f, 0x7c, 0x9b, 0x14, 0x5f, 0xc2,
	0x93, 0x3a, 0x1b, 0x75, 0xa4, 0xcb, 0xc5, 0xb6, 0x20, 0x5e, 0xc2, 0x91, 0x4b, 0x50, 0x1d, 0xea,
	0xb2, 0xd2, 0x61, 0x27, 0xbf, 0x8c, 0x60, 0x74, 0x59, 0x14, 0x68, 0xff, 0x43, 0x49, 0x5f, 0xc2,
	0x11, 0x2e, 0x4b, 0x65, 0xd7, 0x3f, 0x29, 0x3b, 0xbf, 0xc9, 0xa5, 0xf6, 0x95, 0xed, 0xb0, 0xe2,
	0x02, 0x84, 0xc1, 0xe4, 0xee, 0xba, 0x1d, 0xeb, 0x0e, 0xbb, 0x43, 0xa1, 0xef, 0x6a, 0xb4, 0x37,
	0x6a, 0x59, 0xaa, 0x58, 0x52, 0x2d, 0xfc, 0x71, 0x3b, 0x2c, 0xd5, 0x00, 0x3f, 0x44, 0x58, 0x14,
	0xee, 0x7d, 0x7f, 0xd2, 0x16, 0x47, 0xc5, 0x77, 0xd8, 0xbd, 0x48, 0x61, 0xbe, 0xf8, 0x1d, 0x5a,
	0xbc, 0x82, 0xa7, 0xf9, 0x0a, 0x8d, 0x56, 0xc9, 0xbc, 0xb5, 0xf6, 0x3e, 0x87, 0xef, 0xd4, 0xc4,
	0x19, 0x1c, 0xc8, 0x95, 0x54, 0xa9, 0x9c, 0xa5, 0x78, 0x7d, 0x1d, 0x8c, 0x39, 0xb4, 0x49, 0x51,
	0xc4, 0xac, 0x5c, 0x2b, 0x9d, 0xdc, 0xe6, 0xef, 0xd1, 0x04, 0xe0, 0x22, 0x1a, 0x14, 0xad, 0x5b,
	0xbf, 0x70, 0xd5, 0x08, 0x3d, 0x70, 0xeb, 0xee, 0xd2, 0xa8, 0x2a, 0x29, 0xae, 0xd0, 0xc8, 0x04,
	0x83, 0xc7, 0x1c, 0x57, 0x63, 0xaa, 0x67, 0x24, 0xf5, 0x5b, 0x69, 0x12, 0xa5, 0x83, 0x43, 0x36,
	0xf1, 0x86, 0xa0, 0x9e, 0x53, 0x5a, 0x59, 0x25, 0x53, 0x1f, 0x71, 0xe4, 0x7a, 0xae, 0x45, 0x52,
	0xcf, 0x65, 0x52, 0x69, 0x8b, 0x5a, 0xea, 0x08, 0x7d, 0xe4, 0xb1, 0xeb, 0xb9, 0x2d, 0x81, 0xce,
	0x18, 0xc9, 0x62, 0x7e, 0x25, 0x53, 0x22, 0x83, 0x13, 0x77, 0xc6, 0x06, 0xc5, 0x79, 0x72, 0x2d,
	0xc5, 0x66, 0x79, 0xc2, 0x8d, 0xd4, 0xa4, 0x26, 0xbf, 0xf6, 0xe1, 0x31, 0x4d, 0x98, 0xcb, 0xc8,
	0xaa, 0x15, 0x95, 0xe3, 0xdf, 0xb7, 0x25, 0x69, 0xb2, 0x98, 0xf3, 0x4a, 0x03, 0xaf, 0x79, 0x4c,
	0xad, 0x15, 0x35, 0x56, 0x99, 0xba, 0x81, 0x33, 0x08, 0x3b, 0x2c, 0x4d, 0x1d, 0x99, 0xd1, 0x5a,
	0xd5, 0xd4, 0x71, 0x88, 0x86, 0x63, 0x8c, 0x45, 0xc4, 0xad, 0x36, 0x0e, 0xf9, 0x99, 0xd6, 0x9b,
	0xcb, 0xc5, 0x02, 0xf5, 0xa5, 0x1b, 0x2c, 0xc3, 0xb0, 0xc6, 0xa4, 0x39, 0x87, 0x5e, 0x5a, 0x6e,
	0xa4, 0x61, 0x58, 0x63, 0xde, 0xa7, 0x41, 0x69, 0x49, 0x1b, 0x3b, 0xad, 0xc2, 0xa4, 0x95, 0x8b,
	0xd8, 0x69, 0xe0, 0xb4, 0x0a, 0x4f, 0xfe, 0x1a, 0x00, 0xb8, 0xcc, 0x87, 0xd2, 0xa2, 0x38, 0x82,
	0xbe, 0xaa, 0x32, 0xd4, 0x57, 0x71, 0x67, 0xea, 0xf4, 0xb7, 0xa6, 0xce, 0x29, 0xec, 0x15, 0xeb,
	0x6c, 0x96, 0xa7, 0x3e, 0x39, 0x1e, 0x11, 0x9f, 0x49, 0xf3, 0x80, 0x96, 0x53, 0x32, 0x0e, 0x3d,
	0xa2, 0x5e, 0x48, 0x73, 0x9d, 0x4c, 0x5b, 0x5d, 0xe3, 0xe7, 0xcf, 0x96, 0x20, 0xbe, 0x82, 0x4f,
	0x88, 0x7c, 0x57, 0xb9, 0xc5, 0xc7, 0x3b, 0x6b, 0xee, 0x92, 0xc4, 0x37, 0xf0, 0x8c, 0xe8, 0xb7,
	0x5b, 0xfd, 0xe6, 0x7c, 0xba, 0x5b, 0xa4, 0x99, 0x52, 0xcc, 0x73, 0x63, 0xdb, 0xdb, 0x72, 0x5e,
	0xdd, 0xa1, 0x88, 0x6f, 0xe1, 0x94, 0xd9, 0xed, 0x65, 0x9c, 0x69, 0x3f, 0xa2, 0x92, 0x3b, 0x59,
	0xe9, 0x1e, 0xc8, 0x19, 0x79, 0xa7, 0xc6, 0xff, 0x06, 0xe2, 0xbf, 0x47, 0xa4, 0x0a, 0x79, 0x27,
	0xb7, 0x38, 0x6a, 0x44, 0xc6, 0x97, 0x95, 0xbd, 0xd9, 0xc7, 0x83, 0xb0, 0xc3, 0x4e, 0x7e, 0xeb,
	0xc3, 0x49, 0x63, 0xe2, 0xbc, 0x33, 0x31, 0x1a, 0x2a, 0x71, 0xaa, 0x96, 0xfc, 0x5c, 0x9b, 0xa3,
	0xc1, 0xfc, 0xef, 0x2d, 0xd0, 0x74, 0xdb, 0xa8, 0xe3, 0xb6, 0x73, 0x38, 0x4e, 0x37, 0xfb, 0x63,
	0xd3, 0x39, 0x73, 0x74, 0x69, 0x5e, 0xd5, 0x4a, 0x5b, 0x16, 0x5c, 0x59, 0x5a, 0x95, 0x11, 0x7d,
	0x7d, 0x59, 0xfd, 0xac, 0x5c, 0x01, 0x6b, 0x2c, 0x9e, 0xc2, 0x68, 0x61, 0x54, 0x84, 0xbe, 0x4a,
	0x0e, 0xf0, 0x88, 0x63, 0xa7, 0xc4, 0xde, 0x1e, 0xe3, 0x70, 0x43, 0xf0, 0x7d, 0x82, 0xbd, 0x42,
	0xea, 0x81, 0x53, 0x6b, 0x62, 0xf2, 0x67, 0x1f, 0x9e, 0x35, 0x12, 0x1a, 0xaa, 0xe2, 0xe1, 0x75,
	0xae, 0xef, 0x55, 0x22, 0xbe, 0x83, 0xe7, 0x69, 0x5b, 0xb8, 0xc3, 0x6c, 0x91, 0x4a, 0x8b, 0x3e,
	0xc9, 0xa3, 0xf0, 0xe3, 0x01, 0x54, 0x74, 0xeb, 0xd1, 0x0f, 0x32, 0xab, 0x2f, 0x04, 0x4d, 0x8e,
	0x6f, 0x22, 0xa5, 0xcd, 0x9b, 0x7f, 0x17, 0x57, 0x80, 0x2e, 0x2d, 0x4e, 0x60, 0x50, 0x60, 0xe6,
	0xcb, 0x40, 0x8f, 0xee, 0xfe, 0x94, 0x71, 0x3f, 0x8d, 0xaa, 0xfb, 0x13, 0x43, 0x52, 0x30, 0x8f,
	0x59, 0x71, 0x36, 0xab, 0x20, 0xed, 0xe9, 0xbd, 0x34, 0x4a, 0x27, 0xd7, 0x37, 0x2c, 0x3b, 0x47,
	0xb5, 0xb8, 0x76, 0xb6, 0xf6, 0xfd, 0xed, 0xab, 0x22, 0x1a, 0x35, 0x1b, 0xb7, 0x6a, 0xf6, 0x02,
	0x0e, 0xf1, 0xfe, 0x1e, 0x69, 0x60, 0xe2, 0x1b, 0xfa, 0xb4, 0xab, 0x42, 0x9b, 0xbc, 0x7a, 0x0e,
	0x9f, 0x46, 0x79, 0x76, 0xf1, 0xa1, 0xc4, 0xa5, 0x2a, 0x2f, 0x12, 0xb3, 0x88, 0x12, 0xd4, 0x68,
	0xa4, 0xc5, 0xd9, 0x1e, 0x5f, 0x46, 0xbf, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x30, 0x16,
	0x95, 0x9b, 0x0a, 0x00, 0x00,
}
